---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: app-1
  namespace: flux-system
spec:
  interval: 5m0s
  ref:
    branch: fluxcd-2026
  url: https://github.com/cristianpetrache/flux-tests
